; PlatformIO Project Configuration
[env:nano_esp32]
platform = espressif32
board = arduino_nano_esp32
framework = arduino

; Build options
build_flags =
    -Iinclude
    -DDEBUG_MODE=true
    -DSERIAL_BAUD_RATE=115200
    -DBOARD_USES_HW_GPIO_NUMBERS
    -DARDUINO_USB_CDC_ON_BOOT=1

; Library dependencies
lib_deps =
    adafruit/Adafruit LSM6DS @ ^4.7.3
    adafruit/Adafruit BusIO @ ^1.16.2
    https://github.com/WorldFamousElectronics/PulseSensorPlayground.git#1.4.13
    arduino-libraries/ArduinoBLE @ ^1.3.0
    https://github.com/DFRobot/DFRobot_MatrixLidarDistanceSensor.git

; Upload options
upload_speed = 921600
monitor_port = COM7
monitor_speed = 115200