; PlatformIO Project Configuration
[env:nano_esp32]
platform = espressif32
board = nanoesp32
framework = arduino

; Build options
build_flags =
    -DDEBUG_MODE=true
    -DSERIAL_BAUD_RATE=115200

; Library dependencies
lib_deps =
    adafruit/Adafruit LSM6DSOX @ ^1.0.0
    pulsesensor/Arduino PulseSensor Playground @ ^1.5.0
    arduino-libraries/ArduinoBLE @ ^1.3.0
    https://github.com/DFRobot/DFRobot_MatrixLidarDistanceSensor.git

; Serial monitor
monitor_speed = 115200

; Upload options
upload_speed = 921600