import argparse

import pandas as pd
import plotly.graph_objects as go
from plotly.subplots import make_subplots


def build_flag_matrix(df: pd.DataFrame, flag_columns: list[str]) -> pd.DataFrame:
	rows = []
	for idx, flag_name in enumerate(flag_columns):
		for x, val in enumerate(df[flag_name].astype(int).tolist()):
			rows.append({"x": x, "y": idx, "v": val})
	return pd.DataFrame(rows)


def add_virtual_signals(
	df: pd.DataFrame,
	hr_high: int,
	hr_low: int,
	battery_low: int,
	stress_threshold_default: int,
	stress_threshold_conservative: int,
) -> pd.DataFrame:
	for col in ["fall", "high_stress", "obstacle_near", "obstacle_imminent"]:
		if col not in df.columns:
			df[col] = False

	df["heart_above_high"] = df.get("heart_bpm", 0).astype(float) > float(hr_high)
	df["heart_below_low"] = df.get("heart_bpm", 0).astype(float) < float(hr_low)
	df["battery_low"] = df.get("battery_percent", 100).astype(float) <= float(battery_low)

	# Weighted risk score used as a virtual calibration signal.
	df["stress_score"] = (
		df["obstacle_near"].astype(int)
		+ (2 * df["obstacle_imminent"].astype(int))
		+ (2 * df["high_stress"].astype(int))
		+ (4 * df["fall"].astype(int))
		+ df["heart_above_high"].astype(int)
	)

	def map_mode_default(row: pd.Series) -> int:
		if bool(row["fall"]):
			return 3
		if int(row["stress_score"]) >= stress_threshold_default:
			return 2
		if bool(row["battery_low"]):
			return 1
		return 0

	def map_mode_conservative(row: pd.Series) -> int:
		if bool(row["fall"]):
			return 3
		if int(row["stress_score"]) >= stress_threshold_conservative:
			return 2
		if bool(row["battery_low"]):
			return 1
		return 0

	df["virtual_mode_default"] = df.apply(map_mode_default, axis=1)
	df["virtual_mode_conservative"] = df.apply(map_mode_conservative, axis=1)

	if "mode" in df.columns:
		df["mode_delta_default"] = df["virtual_mode_default"] - df["mode"].astype(int)
		df["mode_delta_conservative"] = df["virtual_mode_conservative"] - df["mode"].astype(int)

	return df


def main() -> None:
	parser = argparse.ArgumentParser(description="Advanced Plotly visualization for ProtoSmartCane BLE v2 telemetry")
	parser.add_argument("--file", required=True, help="Path to CSV generated by TestDataRecorder.py")
	parser.add_argument("--rolling-window", type=int, default=10, help="Rolling window size for heart-rate smoothing")
	parser.add_argument("--hr-high", type=int, default=120, help="Virtual high heart-rate threshold")
	parser.add_argument("--hr-low", type=int, default=50, help="Virtual low heart-rate threshold")
	parser.add_argument("--battery-low", type=int, default=20, help="Virtual low-battery threshold")
	parser.add_argument("--stress-threshold-default", type=int, default=2, help="Default calibration threshold for virtual stress mode")
	parser.add_argument("--stress-threshold-conservative", type=int, default=1, help="Conservative calibration threshold for virtual stress mode")
	parser.add_argument("--save-html", action="store_true", help="Save dashboard HTML beside the CSV")
	parser.add_argument("--save-augmented-csv", action="store_true", help="Save CSV copy with virtual signal columns")
	args = parser.parse_args()

	df = pd.read_csv(args.file)
	if df.empty:
		raise RuntimeError("CSV is empty. No data to plot.")

	if "ts" in df.columns:
		df["ts"] = pd.to_datetime(df["ts"], errors="coerce")
		df = df.dropna(subset=["ts"]).reset_index(drop=True)
		x = df["ts"]
		x_title = "Timestamp"
	else:
		x = pd.Series(range(len(df)))
		x_title = "Sample Index"

	if "heart_bpm" in df.columns:
		df["heart_bpm_roll"] = df["heart_bpm"].rolling(window=max(1, args.rolling_window), min_periods=1).mean()

	df = add_virtual_signals(
		df,
		hr_high=args.hr_high,
		hr_low=args.hr_low,
		battery_low=args.battery_low,
		stress_threshold_default=args.stress_threshold_default,
		stress_threshold_conservative=args.stress_threshold_conservative,
	)

	if "ts" in df.columns and len(df) > 1:
		dt = df["ts"].diff().dt.total_seconds().fillna(0.0)
	else:
		dt = pd.Series([0.0] * len(df))

	flag_columns = [c for c in ["fall", "high_stress", "obstacle_near", "obstacle_imminent"] if c in df.columns]

	fig = make_subplots(
		rows=7,
		cols=1,
		shared_xaxes=True,
		vertical_spacing=0.04,
		subplot_titles=(
			"Battery Percent",
			"Heart Rate (Raw + Rolling)",
			"Mode Timeline",
			"Virtual Mode Comparison (Default vs Conservative)",
			"Mode Delta vs Firmware (Virtual - Actual)",
			"Packet Interval / Jitter (s)",
			"Flag Activity Heatmap",
		),
		row_heights=[0.12, 0.18, 0.12, 0.14, 0.12, 0.14, 0.18],
	)

	if "battery_percent" in df.columns:
		fig.add_trace(
			go.Scatter(x=x, y=df["battery_percent"], mode="lines+markers", name="battery_percent", line={"width": 2}),
			row=1,
			col=1,
		)
		fig.add_hline(y=args.battery_low, line_dash="dash", line_color="#f97316", row=1, col=1)

	if "heart_bpm" in df.columns:
		fig.add_trace(
			go.Scatter(x=x, y=df["heart_bpm"], mode="lines", name="heart_bpm", line={"width": 1}),
			row=2,
			col=1,
		)
		fig.add_trace(
			go.Scatter(x=x, y=df["heart_bpm_roll"], mode="lines", name="heart_bpm_roll", line={"width": 3}),
			row=2,
			col=1,
		)
		fig.add_hline(y=args.hr_high, line_dash="dash", line_color="#ef4444", row=2, col=1)
		fig.add_hline(y=args.hr_low, line_dash="dash", line_color="#3b82f6", row=2, col=1)

	if "mode" in df.columns:
		fig.add_trace(
			go.Scatter(x=x, y=df["mode"], mode="lines+markers", name="mode", line={"shape": "hv"}),
			row=3,
			col=1,
		)

	fig.add_trace(
		go.Scatter(x=x, y=df["virtual_mode_default"], mode="lines", name="virtual_mode_default", line={"shape": "hv", "width": 2}),
		row=4,
		col=1,
	)
	fig.add_trace(
		go.Scatter(x=x, y=df["virtual_mode_conservative"], mode="lines", name="virtual_mode_conservative", line={"shape": "hv", "width": 2, "dash": "dot"}),
		row=4,
		col=1,
	)

	if "mode_delta_default" in df.columns:
		fig.add_trace(
			go.Scatter(x=x, y=df["mode_delta_default"], mode="lines", name="mode_delta_default", line={"width": 2}),
			row=5,
			col=1,
		)
	if "mode_delta_conservative" in df.columns:
		fig.add_trace(
			go.Scatter(x=x, y=df["mode_delta_conservative"], mode="lines", name="mode_delta_conservative", line={"width": 2, "dash": "dot"}),
			row=5,
			col=1,
		)
	fig.add_hline(y=0, line_dash="dot", line_color="#94a3b8", row=5, col=1)

	fig.add_trace(
		go.Scatter(x=x, y=dt, mode="lines+markers", name="packet_interval_s", line={"width": 2}),
		row=6,
		col=1,
	)

	if flag_columns:
		matrix = build_flag_matrix(df, flag_columns)
		heat_x = sorted(matrix["x"].unique().tolist())
		heat_y = list(range(len(flag_columns)))
		z = []
		for y_idx in heat_y:
			row_vals = []
			for x_idx in heat_x:
				match = matrix[(matrix["x"] == x_idx) & (matrix["y"] == y_idx)]
				row_vals.append(int(match["v"].iloc[0]) if not match.empty else 0)
			z.append(row_vals)
		fig.add_trace(
			go.Heatmap(
				z=z,
				x=heat_x,
				y=flag_columns,
				zmin=0,
				zmax=1,
				colorscale=[[0.0, "#0f172a"], [1.0, "#22c55e"]],
				showscale=False,
				name="flags",
			),
			row=7,
			col=1,
		)

	fig.update_layout(
		title="ProtoSmartCane BLE v2 Telemetry Dashboard",
		template="plotly_dark",
		height=1500,
		legend={"orientation": "h", "yanchor": "bottom", "y": 1.02, "xanchor": "right", "x": 1},
	)
	fig.update_xaxes(title_text=x_title, row=7, col=1)
	fig.update_yaxes(title_text="Battery %", row=1, col=1)
	fig.update_yaxes(title_text="Heart BPM", row=2, col=1)
	fig.update_yaxes(title_text="Mode", row=3, col=1)
	fig.update_yaxes(title_text="Virtual Mode", row=4, col=1)
	fig.update_yaxes(title_text="Delta", row=5, col=1)
	fig.update_yaxes(title_text="Seconds", row=6, col=1)

	if args.save_augmented_csv:
		augmented_path = f"{args.file}.augmented.csv"
		df.to_csv(augmented_path, index=False)
		print(f"Saved augmented CSV: {augmented_path}")

	if args.save_html:
		html_path = f"{args.file}.dashboard.html"
		fig.write_html(html_path)
		print(f"Saved dashboard: {html_path}")

	fig.show()


if __name__ == "__main__":
	main()