import argparse

import pandas as pd
import plotly.graph_objects as go
from plotly.subplots import make_subplots


IMMINENT_MM = 200
NEAR_MM = 500
FAR_MM = 1000


def classify_zone(mm: float) -> str:
    if pd.isna(mm):
        return "invalid"
    v = float(mm)
    if v <= IMMINENT_MM:
        return "imminent"
    if v <= NEAR_MM:
        return "near"
    if v <= FAR_MM:
        return "far"
    return "clear"


def add_distance_trace(fig, df, x, row: int, col_name: str, label: str, color: str):
    if col_name not in df.columns:
        return

    y = pd.to_numeric(df[col_name], errors="coerce")
    zones = y.apply(classify_zone)

    fig.add_trace(
        go.Scatter(
            x=x,
            y=y,
            mode="lines",
            name=label,
            line={"width": 2.2, "color": color},
            customdata=zones,
            hovertemplate=(
                "%{x}<br>"
                + label
                + ": %{y:.0f} mm<br>"
                + "Zone: %{customdata}<extra></extra>"
            ),
        ),
        row=row,
        col=1,
    )

    # Add threshold guides once per subplot (not in legend)
    fig.add_hline(y=IMMINENT_MM, line_dash="dash", line_color="#ef4444", row=row, col=1)
    fig.add_hline(y=NEAR_MM, line_dash="dash", line_color="#f59e0b", row=row, col=1)
    fig.add_hline(y=FAR_MM, line_dash="dot", line_color="#60a5fa", row=row, col=1)

    # Annotate zone-entry transitions only (avoids clutter)
    prev = None
    entries = 0
    for idx, zone in zones.items():
        if zone != prev and zone in {"imminent", "near", "far"}:
            fig.add_trace(
                go.Scatter(
                    x=[x.iloc[idx]],
                    y=[y.iloc[idx]],
                    mode="markers+text",
                    marker={"size": 8, "color": color},
                    text=[f"{zone.upper()} @ {int(y.iloc[idx])}mm"],
                    textposition="top center",
                    showlegend=False,
                    hoverinfo="skip",
                ),
                row=row,
                col=1,
            )
            entries += 1
        prev = zone
        if entries >= 6:
            break


def main() -> None:
    parser = argparse.ArgumentParser(description="Readable Plotly dashboard for ProtoSmartCane distance-focused offline testing")
    parser.add_argument("--file", required=True, help="Path to CSV generated by TestDataRecorder.py")
    parser.add_argument("--save-html", action="store_true", help="Save dashboard HTML beside the CSV")
    parser.add_argument("--save-augmented-csv", action="store_true", help="Save CSV copy with zone columns")
    parser.add_argument("--hide-imu", action="store_true", help="Hide IMU subplot")
    args = parser.parse_args()

    df = pd.read_csv(args.file)
    if df.empty:
        raise RuntimeError("CSV is empty. No data to plot.")

    if "ts" in df.columns:
        df["ts"] = pd.to_datetime(df["ts"], errors="coerce")
        df = df.dropna(subset=["ts"]).reset_index(drop=True)
        x = df["ts"]
        x_title = "Timestamp"
    else:
        x = pd.Series(range(len(df)))
        x_title = "Sample Index"

    for col in ["matrix_head_mm", "matrix_waist_mm"]:
        if col in df.columns:
            df[col] = df[col].replace(0xFFFF, pd.NA)

    for src, dst in [
        ("ultra_left_mm", "ultra_left_zone"),
        ("ultra_right_mm", "ultra_right_zone"),
        ("matrix_head_mm", "matrix_head_zone"),
        ("matrix_waist_mm", "matrix_waist_zone"),
    ]:
        if src in df.columns:
            df[dst] = df[src].apply(classify_zone)

    imu_available = (not args.hide_imu) and all(c in df.columns for c in ["imu_ax_ms2", "imu_ay_ms2", "imu_az_ms2"])
    rows = 7 + (1 if imu_available else 0)
    subplot_titles = [
        "Battery Percent (%)",
        "Pulse Sensor: BPM + Raw Signal",
        "Current Mode",
        "Ultrasonic Left Distance (mm)",
        "Ultrasonic Right Distance (mm)",
        "8x8 Head Zone Distance (mm)",
        "8x8 Waist Zone Distance (mm)",
    ]
    if imu_available:
        subplot_titles.append("IMU Acceleration (m/s^2)")

    fig = make_subplots(
        rows=rows,
        cols=1,
        shared_xaxes=True,
        vertical_spacing=0.04,
        subplot_titles=tuple(subplot_titles),
    )

    if "battery_percent" in df.columns:
        fig.add_trace(
            go.Scatter(
                x=x,
                y=df["battery_percent"],
                mode="lines+markers",
                name="Battery %",
                line={"width": 2.2, "color": "#22c55e"},
            ),
            row=1,
            col=1,
        )

    if "heart_bpm" in df.columns:
        fig.add_trace(
            go.Scatter(
                x=x,
                y=df["heart_bpm"],
                mode="lines",
                name="Pulse BPM",
                line={"width": 2.2, "color": "#f97316"},
            ),
            row=2,
            col=1,
        )
    if "heart_raw" in df.columns:
        fig.add_trace(
            go.Scatter(
                x=x,
                y=df["heart_raw"],
                mode="lines",
                name="Pulse Raw",
                line={"width": 1.6, "color": "#fb7185"},
            ),
            row=2,
            col=1,
        )

    if "mode" in df.columns:
        fig.add_trace(
            go.Scatter(
                x=x,
                y=df["mode"],
                mode="lines+markers",
                name="Mode",
                line={"width": 2.0, "shape": "hv", "color": "#eab308"},
                hovertemplate="%{x}<br>Mode: %{y}<extra></extra>",
            ),
            row=3,
            col=1,
        )

    add_distance_trace(fig, df, x, 4, "ultra_left_mm", "Ultrasonic Left", "#3b82f6")
    add_distance_trace(fig, df, x, 5, "ultra_right_mm", "Ultrasonic Right", "#06b6d4")
    add_distance_trace(fig, df, x, 6, "matrix_head_mm", "8x8 Head", "#f59e0b")
    add_distance_trace(fig, df, x, 7, "matrix_waist_mm", "8x8 Waist", "#ef4444")

    if imu_available:
        fig.add_trace(
            go.Scatter(x=x, y=df["imu_ax_ms2"], mode="lines", name="IMU ax", line={"color": "#a78bfa", "width": 1.5}),
            row=8,
            col=1,
        )
        fig.add_trace(
            go.Scatter(x=x, y=df["imu_ay_ms2"], mode="lines", name="IMU ay", line={"color": "#c084fc", "width": 1.5}),
            row=8,
            col=1,
        )
        fig.add_trace(
            go.Scatter(x=x, y=df["imu_az_ms2"], mode="lines", name="IMU az", line={"color": "#e879f9", "width": 1.5}),
            row=8,
            col=1,
        )

    fig.update_layout(
        title="ProtoSmartCane Offline Sensor Dashboard",
        template="plotly_dark",
        height=1900 if imu_available else 1650,
        legend={"orientation": "h", "yanchor": "bottom", "y": 1.01, "xanchor": "left", "x": 0},
    )

    fig.add_annotation(
        xref="paper",
        yref="paper",
        x=0,
        y=1.08,
        showarrow=False,
        align="left",
        text=(
            "Distance zones: IMMINENT <= 200 mm, NEAR <= 500 mm, FAR <= 1000 mm, CLEAR > 1000 mm. "
            "Text markers appear only when a signal enters a new zone."
        ),
    )

    fig.update_xaxes(title_text=x_title, row=rows, col=1)
    fig.update_yaxes(title_text="Battery %", row=1, col=1)
    fig.update_yaxes(title_text="Pulse", row=2, col=1)
    fig.update_yaxes(title_text="Mode", row=3, col=1)
    fig.update_yaxes(title_text="mm", row=4, col=1)
    fig.update_yaxes(title_text="mm", row=5, col=1)
    fig.update_yaxes(title_text="mm", row=6, col=1)
    fig.update_yaxes(title_text="mm", row=7, col=1)
    if imu_available:
        fig.update_yaxes(title_text="m/s^2", row=8, col=1)

    if args.save_augmented_csv:
        augmented_path = f"{args.file}.augmented.csv"
        df.to_csv(augmented_path, index=False)
        print(f"Saved augmented CSV: {augmented_path}")

    if args.save_html:
        html_path = f"{args.file}.dashboard.html"
        fig.write_html(html_path)
        print(f"Saved dashboard: {html_path}")

    fig.show()


if __name__ == "__main__":
    main()