#!/usr/bin/env bash
# Build llama.xcframework (static) with mtmd support for iOS device + simulator.
#
# Usage:
#   ./scripts/build_llama_ios.sh [path/to/llama.cpp]
#
# Default llama.cpp path: ~/Desktop/llama.cpp
# Output: ios/Frameworks/llama.xcframework
#
# Requirements:
#   - macOS with Xcode installed
#   - cmake >= 3.28  (pip3 install cmake --user)

set -euo pipefail

LLAMA_CPP="${1:-$HOME/Desktop/llama.cpp}"
REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
OUTPUT_DIR="$REPO_ROOT/ios/Frameworks"
BUILD_ROOT="$LLAMA_CPP/build-ican"

if [ ! -d "$LLAMA_CPP" ]; then
    echo "Error: llama.cpp not found at $LLAMA_CPP"
    echo "Usage: $0 [path/to/llama.cpp]"
    exit 1
fi

echo "==> Building llama.xcframework (STATIC) with mtmd support"
echo "    llama.cpp: $LLAMA_CPP"
echo "    output:    $OUTPUT_DIR/llama.xcframework"

# ── Shared cmake args ──────────────────────────────────────────────────────
CMAKE_COMMON=(
    -G Xcode
    -DLLAMA_BUILD_TOOLS=ON
    -DLLAMA_BUILD_COMMON=ON
    -DLLAMA_BUILD_EXAMPLES=OFF
    -DLLAMA_BUILD_TESTS=OFF
    -DLLAMA_BUILD_SERVER=OFF
    -DGGML_METAL=ON
    -DGGML_METAL_EMBED_LIBRARY=ON
    -DGGML_METAL_USE_BF16=ON
    -DBUILD_SHARED_LIBS=OFF
    -DCMAKE_XCODE_ATTRIBUTE_CODE_SIGN_IDENTITY=""
    -DCMAKE_XCODE_ATTRIBUTE_CODE_SIGNING_REQUIRED=NO
    -DCMAKE_XCODE_ATTRIBUTE_CODE_SIGNING_ALLOWED=NO
)

# ── Static libs to merge ───────────────────────────────────────────────────
STATIC_LIBS=(
    "src/Release-{SUFFIX}/libllama.a"
    "ggml/src/Release-{SUFFIX}/libggml.a"
    "ggml/src/Release-{SUFFIX}/libggml-base.a"
    "ggml/src/Release-{SUFFIX}/libggml-cpu.a"
    "ggml/src/ggml-metal/Release-{SUFFIX}/libggml-metal.a"
    "ggml/src/ggml-blas/Release-{SUFFIX}/libggml-blas.a"
    "tools/mtmd/Release-{SUFFIX}/libmtmd.a"
    "common/Release-{SUFFIX}/libllama-common.a"
)

build_slice() {
    local name="$1"    # e.g. "build-ios-device"
    local sdk="$2"     # e.g. "iphoneos"
    local archs="$3"   # space-separated, e.g. "arm64" or "arm64 x86_64"
    local suffix="$4"  # e.g. "iphoneos" or "iphonesimulator"
    local min_ver="16.0"

    local build_dir="$BUILD_ROOT/$name"
    echo ""
    echo "── Configuring $name (sdk=$sdk archs=$archs) ──"

    local cmake_archs="${archs// /;}"

    cmake -B "$build_dir" \
        "${CMAKE_COMMON[@]}" \
        -DCMAKE_SYSTEM_NAME=iOS \
        -DCMAKE_OSX_SYSROOT="$sdk" \
        -DCMAKE_OSX_ARCHITECTURES="$cmake_archs" \
        -DCMAKE_OSX_DEPLOYMENT_TARGET="$min_ver" \
        "$LLAMA_CPP"

    echo "── Building $name ──"
    cmake --build "$build_dir" --config Release --target mtmd -- -quiet

    # ── Merge all static libs into one fat combined.a ─────────────────────
    local lib_paths=()
    for pattern in "${STATIC_LIBS[@]}"; do
        local path="$build_dir/${pattern//\{SUFFIX\}/$suffix}"
        if [ -f "$path" ]; then
            lib_paths+=("$path")
        else
            echo "    Warning: $path not found, skipping"
        fi
    done

    local out_a="$build_dir/libllama_combined.a"
    echo "── Merging ${#lib_paths[@]} static libs → libllama_combined.a ──"
    xcrun libtool -static -o "$out_a" "${lib_paths[@]}" 2>/dev/null

    echo "── Slice $name done: $out_a ──"
}

# ── Build both slices ──────────────────────────────────────────────────────
build_slice "build-ios-device" "iphoneos"        "arm64"        "iphoneos"
build_slice "build-ios-sim"    "iphonesimulator" "arm64 x86_64" "iphonesimulator"

# ── Assemble .xcframework from two .a files + headers ─────────────────────
# A static xcframework just needs:
#   <name>.xcframework/
#     ios-arm64/
#       libllama.a
#       Headers/       ← all public headers
#     ios-arm64_x86_64-simulator/
#       libllama.a
#       Headers/
#     Info.plist       ← generated by xcodebuild

DEVICE_A="$BUILD_ROOT/build-ios-device/libllama_combined.a"
SIM_A="$BUILD_ROOT/build-ios-sim/libllama_combined.a"

# Copy headers to a staging directory (same set used for both slices)
HEADERS_DIR="$BUILD_ROOT/headers"
rm -rf "$HEADERS_DIR" && mkdir -p "$HEADERS_DIR"
cp "$LLAMA_CPP/include/llama.h"           "$HEADERS_DIR/"
cp "$LLAMA_CPP/ggml/include/"*.h          "$HEADERS_DIR/"
cp "$LLAMA_CPP/tools/mtmd/mtmd.h"         "$HEADERS_DIR/"
cp "$LLAMA_CPP/tools/mtmd/mtmd-helper.h"  "$HEADERS_DIR/"

# Write a module.modulemap so `import llama` works in Swift
cat > "$HEADERS_DIR/module.modulemap" <<'MODULEMAP'
framework module llama {
    umbrella header "llama.h"
    header "mtmd.h"
    header "mtmd-helper.h"
    export *
    module * { export * }
}
MODULEMAP

# Place headers next to each .a so xcodebuild -create-xcframework picks them up
mkdir -p "$BUILD_ROOT/build-ios-device/headers"
mkdir -p "$BUILD_ROOT/build-ios-sim/headers"
cp -r "$HEADERS_DIR/"* "$BUILD_ROOT/build-ios-device/headers/"
cp -r "$HEADERS_DIR/"* "$BUILD_ROOT/build-ios-sim/headers/"

# Remove old xcframework
mkdir -p "$OUTPUT_DIR"
rm -rf "$OUTPUT_DIR/llama.xcframework"

echo ""
echo "── Creating static llama.xcframework ──"
xcodebuild -create-xcframework \
    -library "$DEVICE_A" -headers "$BUILD_ROOT/build-ios-device/headers" \
    -library "$SIM_A"    -headers "$BUILD_ROOT/build-ios-sim/headers" \
    -output "$OUTPUT_DIR/llama.xcframework"

echo ""
echo "==> Done: $OUTPUT_DIR/llama.xcframework"
echo ""
echo "In Xcode:"
echo "  1. Remove the old llama.xcframework from Runner target"
echo "  2. Add ios/Frameworks/llama.xcframework → Embed: Do Not Embed (it is static)"
echo "  3. Build Settings → Other Linker Flags → -ObjC (if not already there)"
echo "  4. Cmd+B"
